# Generated by Django 4.0.4 on 2022-05-22 12:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_get_back_money', '0002_alter_getbackmoney_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getbackmoney',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
